/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CennikNaprawRouteImport } from './routes/cennik-napraw'
import { Route as SerwisIphoneMokotowRouteImport } from './routes/serwis-iphone-mokotow'
import { Route as SerwisIphonePragaRouteImport } from './routes/serwis-iphone-praga'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as UslugiServiceSlugRouteImport } from './routes/uslugi/$serviceSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CennikNaprawRoute = CennikNaprawRouteImport.update({
  id: '/cennik-napraw',
  path: '/cennik-napraw',
  getParentRoute: () => rootRouteImport,
} as any)
const SerwisIphoneMokotowRoute = SerwisIphoneMokotowRouteImport.update({
  id: '/serwis-iphone-mokotow',
  path: '/serwis-iphone-mokotow',
  getParentRoute: () => rootRouteImport,
} as any)
const SerwisIphonePragaRoute = SerwisIphonePragaRouteImport.update({
  id: '/serwis-iphone-praga',
  path: '/serwis-iphone-praga',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiServiceSlugRoute = UslugiServiceSlugRouteImport.update({
  id: '/uslugi/$serviceSlug',
  path: '/uslugi/$serviceSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cennik-napraw': typeof CennikNaprawRoute
  '/serwis-iphone-mokotow': typeof SerwisIphoneMokotowRoute
  '/serwis-iphone-praga': typeof SerwisIphonePragaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/uslugi/$serviceSlug': typeof UslugiServiceSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cennik-napraw': typeof CennikNaprawRoute
  '/serwis-iphone-mokotow': typeof SerwisIphoneMokotowRoute
  '/serwis-iphone-praga': typeof SerwisIphonePragaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/uslugi/$serviceSlug': typeof UslugiServiceSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cennik-napraw': typeof CennikNaprawRoute
  '/serwis-iphone-mokotow': typeof SerwisIphoneMokotowRoute
  '/serwis-iphone-praga': typeof SerwisIphonePragaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/uslugi/$serviceSlug': typeof UslugiServiceSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cennik-napraw'
    | '/serwis-iphone-mokotow'
    | '/serwis-iphone-praga'
    | '/blog/$slug'
    | '/uslugi/$serviceSlug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cennik-napraw'
    | '/serwis-iphone-mokotow'
    | '/serwis-iphone-praga'
    | '/blog/$slug'
    | '/uslugi/$serviceSlug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/cennik-napraw'
    | '/serwis-iphone-mokotow'
    | '/serwis-iphone-praga'
    | '/blog/$slug'
    | '/uslugi/$serviceSlug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CennikNaprawRoute: typeof CennikNaprawRoute
  SerwisIphoneMokotowRoute: typeof SerwisIphoneMokotowRoute
  SerwisIphonePragaRoute: typeof SerwisIphonePragaRoute
  BlogSlugRoute: typeof BlogSlugRoute
  UslugiServiceSlugRoute: typeof UslugiServiceSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cennik-napraw': {
      id: '/cennik-napraw'
      path: '/cennik-napraw'
      fullPath: '/cennik-napraw'
      preLoaderRoute: typeof CennikNaprawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serwis-iphone-mokotow': {
      id: '/serwis-iphone-mokotow'
      path: '/serwis-iphone-mokotow'
      fullPath: '/serwis-iphone-mokotow'
      preLoaderRoute: typeof SerwisIphoneMokotowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serwis-iphone-praga': {
      id: '/serwis-iphone-praga'
      path: '/serwis-iphone-praga'
      fullPath: '/serwis-iphone-praga'
      preLoaderRoute: typeof SerwisIphonePragaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/$serviceSlug': {
      id: '/uslugi/$serviceSlug'
      path: '/uslugi/$serviceSlug'
      fullPath: '/uslugi/$serviceSlug'
      preLoaderRoute: typeof UslugiServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CennikNaprawRoute: CennikNaprawRoute,
  SerwisIphoneMokotowRoute: SerwisIphoneMokotowRoute,
  SerwisIphonePragaRoute: SerwisIphonePragaRoute,
  BlogSlugRoute: BlogSlugRoute,
  UslugiServiceSlugRoute: UslugiServiceSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
